Sprint-13
Tulpanchik2906/java-shareit pull request #1
Opened 2023-05-15 12:22 UTC by Tulpanchik2906

2023-05-16 13:29 UTC, Fleaman777 requested changes

2023-05-16 13:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> findAllByUserId(@RequestHeader("X-Sharer-User-Id") Long userId) {
X-Sharer-User-Id - можно было бы вынести в константу

2023-05-16 13:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Long id;// уникальный идентификатор вещи;
можно сказать, хорошо написанный код, сам себя документирует, 
что в принципе применимо и к названиям переменных, 
если переменная хорошо названа, то нет необходимости ее как-то дополнительно комментировать

а у тебя они имеют хорошие названия)

2023-05-16 13:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    }
как-то многовато пустых строк

аналагично в др местах

2023-05-16 13:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validExistUser(Long userId) {
validate... будет грамотней, 
valid - это не глагол

2023-05-17 14:52 UTC, Fleaman777 approved these changes

2023-05-26 13:40 UTC, Tulpanchik2906 commented
с этого спринта хватит эксперементов

2023-05-26 13:40 UTC, merged