15-ый спринт
Tulpanchik2906/java-shareit pull request #4
Opened 2023-06-05 12:46 UTC by Tulpanchik2906

2023-06-15 12:29 UTC, Fleaman777 requested changes

2023-06-15 12:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                // а потом сделать отсечение через функцию limit
здесь получается, комментариев больше чем самого кода, что в итоге отвлекает от чтение самой программы, 

если совсем не хочется удалять коммаентарии, то можно было бы кратко перед методом или основным блоком написать, что именно делается в методе, 
все остальное должно быть понятно из кода

2023-06-15 12:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (requestId != null) {
это условие можно было бы инвертировать и соответственно сразу вернуть null, что бы не оборачивать последующих код в блок { }

2023-06-15 12:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                throw new NotFoundException("Не найден запрос с id:" + requestId);
у Optional класса есть хороший метод orElseThrow 
отлично сюда впишется и сократит количество кода

2023-06-15 12:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/util/PageUtil.java
> +    }
хороший утилитарный класс

2023-06-15 12:29 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        headers.add(X_SHARER_USER_ID, String.valueOf(userId));
подготовку Header можно было бы вынести в метод setUp

2023-06-15 12:29 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +        headers.add(X_SHARER_USER_ID, String.valueOf(userId));
аналагогично с пред комментарием

2023-06-15 12:29 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/storage/ItemRepositoryTest.java
> +    private void preSearchNameTest() {
в тестах тоже хорошо бы придерживаться порядка методов, 

сначла public, потом private

2023-06-15 12:29 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/util/handler/ErrorHandlerTest.java
> +}
я так понимаю, тесты на хэндлер, это больше для покрытия.

вообще их можно не делать, если в них не содержиться какая-та кастомная логика, 

это примерно так же, как писать тесты на геттеры и сетторы, если они не делают чего-то специфического

2023-06-15 13:21 UTC, Tulpanchik2906 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                // а потом сделать отсечение через функцию limit
Без комментариев я не вспомню потом, почему я так сделала.

2023-06-15 13:24 UTC, Tulpanchik2906 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                // а потом сделать отсечение через функцию limit
Без них я потом не вспомню, почему я так написала.

2023-06-15 13:28 UTC, Tulpanchik2906 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        headers.add(X_SHARER_USER_ID, String.valueOf(userId));
Я ее оставлю, конкретно в этом классе, есть заглушка сервиса, но если ее убрать, то у этого хедера появляется большое влияние на результат, и можно туда разных юзеров закидывать, и получать соответственно разный результат.

2023-06-16 13:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                // а потом сделать отсечение через функцию limit
хорошо, понял тебя

но в продакшен коде это конечно будет не позволительно, и придется вспоминать по самому коду)

2023-06-16 13:42 UTC, Fleaman777 approved these changes

2023-06-16 19:55 UTC, merged